#!/bin/bash

# NIFTY 100 tickers (NSE)
tickers=(
  RELIANCE HDFCBANK BHARTIARTL SBIN ICICIBANK TCS BAJFINANCE LT
  HINDUNILVR INFY LICI MARUTI SUNPHARMA AXISBANK KOTAKBANK "M&M"
  ITC TITAN NTPC HCLTECH ULTRACEMCO ASIANPAINT ONGC ADANIPORTS
  NESTLEIND POWERGRID WIPRO TATAMOTORS BAJAJ_AUTO COALINDIA
  TATACONSUM APOLLOHOSP TECHM JSWSTEEL GRASIM HINDALCO BPCL
  TRENT DRREDDY ZYDUSLIFE ADANIENT BEL VEDL EICHERMOT SBILIFE
  DLF LTIM PIDILITIND TVSMOTOR BRITANNIA CIPLA PFC BANKBARODA
  CHOLAFIN PNB SHRIRAMFIN TATAPOWER TORNTPHARM GAIL IRFC CANBK
  REC AMBUJACEM ADANIGREEN VARUNBEV INDUSINDBK JINDALSTEL ICICIGI
  SIEMENS ABB HAVELLS MUTHOOTFIN DABUR SRF BERGEPAINT NAVINFLUOR
  BAJAJHFL GODREJCP JIOFIN MAXHEALTH INDHOTEL BOSCHLTD SHREECEM
  COLPAL PAGEIND BAJAJHLDNG NAUKRI ADANITRANS 3MINDIA SUZLON
  PETRONET POLICYBZR ALKEM JUBLFOOD ASTRAZEN EXIDEIND GLAND
  BAJAJELEC CROMPTON RADIOCITY
)

for ticker in "${tickers[@]}"; do
  # Create a safe filename (replace & with _)
  filename=$(echo "$ticker" | tr '[:upper:]' '[:lower:]' | tr '&' '_')
  echo "=== Downloading NSE:$ticker ==="
  tv symbol "NSE:$ticker"
  tv goto 2010-01-01 --to 2026-03-05
  tv download -o "data/nse/${filename}.csv"
  echo "=== Done: $ticker ==="
  echo ""
  sleep 5
done

echo "All NSE downloads complete!"
